CREATE TABLE city (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    LATITUDE DOUBLE PRECISION,
    LONGITUDE DOUBLE PRECISION,
    WIKI_DATA_ID VARCHAR(255) NOT NULL,
    COUNTRY_ISO_2 VARCHAR(2)
);
